---
- name: Install and start apache httpd 
  hosts: web 
  tasks:
  - name: httpd package is installed 
    yum:
      name: httpd 
      state: latest 
  - name: correct index.html is present 
    copy:
      src: files/index.html
      dest: /var/www/html/index.html
  - name: httpd is started 
    service:
      name: httpd 
      state: started 
      enabled: true 
