---
- name: Installs a package and prints the result 
  hosts: all 
  tasks: 
  - name: Install the package 
    yum: 
      name: httpd 
      state: installed 
    register: install_result 
  - name: debug 
    debug:
      var: install_result 
