---
- name: Enable intranet services 
  hosts: servera.lab.example.com 
  become: yes 
  tasks:
  - name: latest version of httpd and firewalld installed 
    yum:
      name: 
        - httpd
        - firewalld
      state: latest 
  - name: test html page is installed 
    copy:
      content: "Welcome to the example.com intranet!\n"
      dest: /var/wwww/html/index.html
  - name: firewalld enabled and running 
    service:
      name: firewalld
      state: started 
      enabled: true 
  - name: firewalld permits access to httpd service 
    firewalld:
      service: http 
      permanent: true 
      state: enabled 
      immediate: true 
  - name: httpd enabled and running 
    service:
      name: firewalld
      state: started 
      enabled: true 

- name: Test intranet web server 
  hosts: localhost 
  become: no
  tasks:
  - name: connect to intranet web server 
    uri:
      url: http://servera.lab.example.com
      return_content: yes 
      status_code: 200
